"""add tables

Revision ID: 7c2df648eb37
Revises: 
Create Date: 2026-01-14 09:44:07.612597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c2df648eb37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_flow_statements_id'), table_name='cash_flow_statements')
    op.drop_table('cash_flow_statements')
    op.drop_index(op.f('ix_balance_sheets_id'), table_name='balance_sheets')
    op.drop_table('balance_sheets')
    op.drop_index(op.f('ix_income_statements_id'), table_name='income_statements')
    op.drop_table('income_statements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('income_statements',
    sa.Column('revenue', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('gross_profit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('operating_expenses', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('operating_income', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('finance_costs', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('profit_before_tax', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('tax', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_income', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('eps', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('period', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('report_analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_analysis_id'], ['report_analysis.id'], name=op.f('fk_income_statements_report_analysis_id_report_analysis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_statements')),
    sa.UniqueConstraint('report_analysis_id', name=op.f('uq_income_statements_report_analysis_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_income_statements_id'), 'income_statements', ['id'], unique=False)
    op.create_table('balance_sheets',
    sa.Column('current_assets', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('non_current_assets', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_assets', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('current_liabilities', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('non_current_liabilities', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_liabilities', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('equity', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('period', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('report_analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_analysis_id'], ['report_analysis.id'], name=op.f('fk_balance_sheets_report_analysis_id_report_analysis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_sheets')),
    sa.UniqueConstraint('report_analysis_id', name=op.f('uq_balance_sheets_report_analysis_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_balance_sheets_id'), 'balance_sheets', ['id'], unique=False)
    op.create_table('cash_flow_statements',
    sa.Column('operating_cash_flow', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('investing_cash_flow', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('financing_cash_flow', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_change_in_cash', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('beginning_cash', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('ending_cash', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('period', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('report_analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_analysis_id'], ['report_analysis.id'], name=op.f('fk_cash_flow_statements_report_analysis_id_report_analysis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_flow_statements')),
    sa.UniqueConstraint('report_analysis_id', name=op.f('uq_cash_flow_statements_report_analysis_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_cash_flow_statements_id'), 'cash_flow_statements', ['id'], unique=False)
    # ### end Alembic commands ###
